### ISSUE TITLE
hackrf_sweep functionality

### ISSUE THREAD

**Issue by DanielCraig** [kpreid/shinysdr#102]
I was reading this [paper](https://www.blackhat.com/docs/us-17/wednesday/us-17-Ossmann-Whats-On-The-Wireless-Automating-RF-Signal-Identification-wp.pdf) and trying to figure how to perform the sweep with ShinySDR. From the picture in the paper, it look like it's using a file input. Is there a "live" sweep option?

Also, there's a comment about implementing Automatic Modulation Classification (AMC). Would this prospect happen to use the gr-inspector blocks?

**Comment by kpreid** [comment]
I was contacted at the beginning of that project but none of the work described in that paper has been shared with me, so you will have to talk with them about the details.
