### ISSUE TITLE
the "L" for left on audio pan is mispla

### ISSUE THREAD

**Issue by ClaudeMa** [kpreid/shinysdr#103]
Hello
Just a very little issue
The "L" letter for left audio pan is misplaced
see screenshot
i use Firefox 58.0.1 (64 bits)
best reguards
Claude
![capture](https://user-images.githubusercontent.com/2773730/35776517-3b4d1760-099e-11e8-86c0-cb71f4b38fa2.PNG)

**Comment by kpreid** [comment]
Should be fixed in commit 49b53cdfe55164322f562e45d85e45d606e1e891.

I also fixed a few other things that were broken on Firefox. (Firefox used to just not work at all due to some WebSocket incompatibility not in my code, so ShinySDR is not at all well tested there.)
