### ISSUE TITLE
ARM device

### ISSUE THREAD

**Issue by AlanJan** [kpreid/shinysdr#114]
Hi ,

First of all my compliments for ShinySDR! ShinySDR is a great program, its match my need! I have been test it for a while on a Beelink X2,  its a low power comsumption device (like 1watt) and with ARMv7 architecture (Allwinner H3 quad core ARM Cortex A7) and ArmbianOS. is runs with domoticz and ShinySDR at the same time that gives me a CPU load of 45% and a CPU temperature of 55.8 C.(with extra holes in the cabinet) The only (low prio)thing is fm stereo and AM, in this modes the CPU load rizes to 80%.

The next thing i want to do, is install ShinySDR on a M96X PLUS a Amlogic S912 device, low budget mediaplayer with low power comsumpsion. it has a 2.0GHz Cortex A53 Octa Core and 2 Gb ram and 16Gb rom for a low price of $55. it can be flashed it with Armbian distro (debian).
The modulators of ShinySDR is the couse of the hi cpu load. when i remove the receiver module on the webpage, its give me a load of 17%. I am curious what the result is with M96X PLUS. 

It would be fine if we can adjust the bandwidth on the webpage like SDRSharp does in the tuning needle.

to be continued.

regards,
Alan

**Comment by kpreid** [comment]
CPU use is covered by #17 and I don't see any other requests here.
