### ISSUE TITLE
Instructions not current?

### ISSUE THREAD

**Issue by ofadam** [kpreid/shinysdr#138]
I was following along with the instructions here:

https://shinysdr.switchb.org/manual/installation

And noticed that the "fetch-js-deps" portion of the installation doesn't seem to be accurate any longer. Are there other parts of this document that also need updated?

**Comment by kpreid** [comment]
Thanks for catching this! The manual has already been updated upstream (<https://github.com/kpreid/shinysdr/blob/master/shinysdr/i/webstatic/manual/installation.html>) but pushing it to https://shinysdr.switchb.org/ is a manual process which I forgot to do. If you want to follow the latest copy, for now you can download and view that HTML or read it in source form.

**Comment by kpreid** [comment]
https://shinysdr.switchb.org/manual/installation has been updated. Please let me know if you have any other trouble!
