### ISSUE TITLE
fetch_deps not working?

### ISSUE THREAD

**Issue by eadmaster** [kpreid/shinysdr#141]
when i run  `python setup.py fetch_deps` it downloads  `text.js` and `require.js` files but the  `measviz, jasmine, etc.`  subdirs stays empty.

**Comment by kpreid** [comment]
Did you perform a `git clone` to obtain ShinySDR? The parts you mention will not work if you downloaded a zip from GitHub because the submodule information will be missing.

If that's not the problem, then please try running just the command `git submodule update --init` and post its output.

**Comment by eadmaster** [comment]
> Did you perform a git clone to obtain ShinySDR?

thank you, that solved the problem!
