### ISSUE TITLE
Can we (I) have frequency offset added ?

### ISSUE THREAD

**Issue by zanco** [kpreid/shinysdr#155]
Running shinysdr with rtl device, ppm set, but running behind a satellite LNB with 9.750 GHz Local Oscillator 

Would be nice if I could add this offset and have the direct frequency on my screen without having windows calculator open to do the math for me :-)

Thanks,

Ben - PE2BZ from the Netherlands

**Comment by kpreid** [comment]
Combine `shinysdr.devices.FrequencyShift(-9.750e9)` with your RTL device in the config file.

This is documented in [the "special-purpose devices" section of the manual](https://shinysdr.switchb.org/manual/configuration#special).

**Comment by zanco** [comment]
Thank for the explanation !

The frequency display(ed) is not ready for frequencies over 9.9 GHz is that right ?

**Comment by kpreid** [comment]
It shouldn't be hard to change.

The maximum digits are set here in this loop:  https://github.com/kpreid/shinysdr/blob/master/shinysdr/i/webstatic/client/widgets/basic.js#L622

The font size will probably have to be reduced too: https://github.com/kpreid/shinysdr/blob/master/shinysdr/i/webstatic/client/ui.css#L513
