### ISSUE TITLE
setup.py fail

### ISSUE THREAD

**Issue by mathisono** [kpreid/shinysdr#22]
pi@kj6dzbSDR ~/shinysdr $ ./setup.py
from: can't read /var/mail/setuptools
./setup.py: line 23: syntax error near unexpected token `newline'
./setup.py: line 23: `setup('

**Comment by kpreid** [comment]
setup.py is not written to be executable. The usual way to run it is `python setup.py`, not `./setup.py`. You'll also need to give it a command, for example

    python setup.py install

I've added a `#!` to it so that it doesn't fail in this cryptic way.
