### ISSUE TITLE
the modification of GUI

### ISSUE THREAD

**Issue by mitchell520** [kpreid/shinysdr#36]
Hi,sir
  I wanna modify your GUI in brower. Can you tell me in which file I can do this?

**Comment by kpreid** [comment]
The GUI is partly generated from what the server's objects export, and partly controlled by explicit code on the client.

For the server side, the particular class (`Device`, `Receiver`, `MonitorSink`, etc.) will have things marked with `@exported_state` + `@setter`, or using the `state_def` method.

For the client side, the top-level GUI structure can be found in `shinysdr/webparts/index.template.xhtml` and the code which implements specific widgets (like the spectrum view or the formatting of a receiver) is in `shinysdr/webstatic/client/widgets.js`

Next to `widgets.js` you will also find `widget.js` which contains the GUI "framework" that handles building the structure and updating it.

It is all a bit of a mess, I'll say.
