### ISSUE TITLE
IQ Reversed on HackRF

### ISSUE THREAD

**Issue by aldude999** [kpreid/shinysdr#46]
I've noticed on the HackRF, there doesn't seem to be a way to filp the IQ, and it seems to be reversed. Does anybody know how I could flip the IQ with ShinySDR?

**Comment by devnulling** [comment]
@aldude999 Have you updated the CPLD & firmware on the HackRF? There was a commit ~2 years ago that flipped the IQ in the HackRF CPLD. 

https://github.com/mossmann/hackrf/wiki/Updating-Firmware

**Comment by aldude999** [comment]
Yes, I am on the newest version, hackrf_info reports
`Found HackRF board 0:
USB descriptor string: 0000000000000000457863c825272d1f
Board ID Number: 2 (HackRF One)
Firmware Version: 2015.07.2
Part ID Number: 0xa000cb3c 0x00584353
Serial Number: 0x00000000 0x00000000 0x457863c8 0x25272d1f
`

**Comment by devnulling** [comment]
@aldude999 Did you update the CPLD image as well, and not just the firmware? (Step 2 in the link above). I ran into this same issue with IQ being flipped, because the CPLD image wasn't updated.

**Comment by devnulling** [comment]
Just for reference, the relevant git commit - https://github.com/mossmann/hackrf/commit/8e387e5489077d838e889179612c266830ed3913

**Comment by aldude999** [comment]
Thanks so much for the help, I guess I never flashed the CPLD file when I updated the firmware. Flashed it and now it's working with no problems!

**Comment by kpreid** [comment]
@devnulling Thanks for helping!
