### ISSUE TITLE
Maximum spectrum width is 10MHz

### ISSUE THREAD

**Issue by bdn76** [kpreid/shinysdr#55]
How to increase spectrum width for full Hackrf bandwidth (20MHz) ?

**Comment by kpreid** [comment]
* Make sure the sample rate is set in the configuration file, i.e. `OsmoSDRDevice('hackrf=', sample_rate=20e6)`
* The HackRF One has a variable filter. In the ShinySDR UI just below the gain controls, click “▸ more” and then adjust the “Analog bandwidth” slider as needed.

    Remember that a too-wide setting will cause aliasing (signals wrapping around the displayed spectrum); there should be some visible dropoff at the left and right edges.
