### ISSUE TITLE
Provide some screenshots or a video demo?

### ISSUE THREAD

**Issue by Naereen** [kpreid/shinysdr#56]
Hi,
It's hard to know how advanced and usable is your project, without trying it ourself.

Could you provide some screenshots of the UI, in the `README.md`, and/or a video demo showing quickly how it looks and how to use it?

**Comment by kpreid** [comment]
This is covered by #39.

**Comment by Naereen** [comment]
No, not really, I am not talking about the website but about the main `README.md` document.

**Comment by kpreid** [comment]
Most of the content of the README is going to move to the web site anyway, and there will be a link. There might end up being a screenshot etc. anyway, but it is definitely _part of that project_.
