### ISSUE TITLE
Measviz.css and measviz.js Missing

### ISSUE THREAD

**Issue by aldude999** [kpreid/shinysdr#60]
I just installed shinysdr from scratch and when I connect a client to the server, it stalls at "Loading client...."

When checking the console, I get "Failed to load resource: the server responded with a status of 404" for http://ip-address:8100/client/measviz.css and
http://ip-address:8100/client/measviz.js

I've run fetch-js-deps.sh and setup.py install and created a folder and this is with a fresh install of Debian as well. the files exist in the deps folder too.

**Comment by kpreid** [comment]
The list of files to install was not complete. Should be fixed in 240a399.

**Comment by aldude999** [comment]
Cool, it's working! Now if only I could figure out how to get gr-dsd working properly. :P
